version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "12:34"
  pull-request-branch-name:
    separator: "-"
  open-pull-requests-limit: 10
  target-branch: custom
  ignore:
  - dependency-name: grunt-contrib-uglify
    versions:
    - 5.0.1
  - dependency-name: grunt-cli
    versions:
    - 1.4.1
  - dependency-name: nanoid
    versions:
    - 3.1.21
  - dependency-name: eslint
    versions:
    - 7.21.0
    - 7.22.0
  - dependency-name: grunt-contrib-cssmin
    versions:
    - 4.0.0
